---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

# Install the Container Runtime Engine

# Docker
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    when: c_eng | int == 1

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    when: c_eng | int == 1

# Specify Docker version
# To list the available versions in the repo run # apt-cache madison docker-ce
  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce=5:20.10.7~3-0~ubuntu-xenial
      - docker-ce-cli=5:20.10.7~3-0~ubuntu-xenial
      - containerd.io=1.4.6-1
    when: c_eng | int == 1
      
  - name: Add user to docker group
    user:
      name: "{{ user }}"
      group: docker
    when: c_eng | int == 1
  
  - name: Set Docker cgroup driver to systemd
    blockinfile:
      path: /etc/docker/daemon.json
      create: yes 
      block: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
    when: c_eng | int == 1

  - name: Delete Ansible marker in /etc/docker/daemon.json
    lineinfile:
      path: /etc/docker/daemon.json
      regexp: "ANSIBLE" 
      state: absent
    when: c_eng | int == 1

# containerd
  - name: Set-up containerd prerequisites
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
      overlay
      br_netfilter
      EOF
      sudo modprobe overlay
      sudo modprobe br_netfilter
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF
      sudo sysctl --system
    when: c_eng | int == 2

  - name: Install containerd
    shell: |
      wget https://github.com/containerd/containerd/releases/download/v1.5.5/cri-containerd-cni-1.5.5-linux-amd64.tar.gz

      sudo tar --no-overwrite-dir -C / -xzf cri-containerd-cni-1.5.5-linux-amd64.tar.gz
      rm *
      
      sudo systemctl daemon-reload
      sudo systemctl start containerd
    when: c_eng | int == 2

# CRI-O
  - name: Set-up CRI-O prerequisites
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
      overlay
      br_netfilter
      EOF
      sudo modprobe overlay
      sudo modprobe br_netfilter
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF
      sudo sysctl --system
    when: c_eng | int == 3

  - name: Add CRI-O repositories
    shell: |
      export OS=xUbuntu_20.04
      export VERSION=1.20

      echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
    
    when: c_eng | int == 3 

  - name: Add CRI-O repository key
    shell: |
      export OS=xUbuntu_20.04
      export VERSION=1.20

      curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -
      curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -
    when: c_eng | int == 3 

  - name: Install CRI-O
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - cri-o
      - cri-o-runc
    when: c_eng | int == 3
      
  - name: Enable CRI-O service
    shell: |
      sudo systemctl daemon-reload
      sudo systemctl enable crio --now
    when: c_eng | int == 3

  - name: Use cgroup driver for CRI-O 1/2
    ansible.builtin.lineinfile:
      path: /etc/crio/crio.conf
      regexp: '^conmon_cgroup ='
      line: conmon_cgroup = "pod"
    when: c_eng | int == 3

  - name: Use cgroup driver for CRI-O 2/2
    ansible.builtin.lineinfile:
      path: /etc/crio/crio.conf
      regexp: '^cgroup_manager = "systemd"'
      line: cgroup_manager = "cgroupfs"
    when: c_eng | int == 3

  - name: Restart crio
    service:
      name: crio
      daemon_reload: yes
      state: restarted
    when: c_eng | int == 3

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap for the kubelet
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

# Kubernetes version = 1.20.0
  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet=1.20.0-00
        - kubeadm=1.20.0-00
        - kubectl=1.20.0-00

  - name: Avoid automatic updates for kuebelt, kubeadm, and kubectl
    command: sudo apt-mark hold kubelet kubeadm kubectl

  - name: Configure node ip for the kubelet
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      create: yes
  
# Install etcd CLI utility
  - name: Install etcdctl
    apt: 
      name: etcd-client
      update_cache: yes
      state: latest

  - name: Restart Docker service
    shell: |
      systemctl enable docker
      systemctl daemon-reload
      systemctl restart docker
    when: c_eng | int == 1

  - name: Create systemd file for containerd
    blockinfile:
      path: /etc/systemd/system/kubelet.service.d/0-containerd.conf
      create: yes 
      block: |
        [Service]
        Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock"
    when: c_eng | int == 2 

  - name: Delete Ansible marker in 0-containerd.conf
    lineinfile:
      path: /etc/systemd/system/kubelet.service.d/0-containerd.conf
      regexp: "ANSIBLE" 
      state: absent
    when: c_eng | int == 2

  - name: Restart containerd
    service:
      name: containerd
      daemon_reload: yes
      state: restarted
    when: c_eng | int == 2 

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

### Single-master cluster ###
# Kubernetes Master node bootstrap with kubeadm and Docker
  - name: Initialize the Kubernetes cluster using kubeadm and Docker
    command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name {{ hostname }} --pod-network-cidr=192.168.0.0/16
    when: c_eng | int == 1 and n_m_nodes | int == 1

# Kubernetes Master node bootstrap with kubeadm and containerd
  - name: Initialize the Kubernetes cluster using kubeadm and containerd
    command: kubeadm init --cri-socket=/run/containerd/containerd.sock --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name {{ hostname }} --pod-network-cidr=192.168.0.0/16
    when: c_eng | int == 2 and n_m_nodes | int == 1

# Kubernetes Master node bootstrap with kubeadm and CRI-O
  - name: Initialize the Kubernetes cluster using kubeadm and CRI-O
    command: kubeadm init --cri-socket=/var/run/crio/crio.sock --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name {{ hostname }} --pod-network-cidr=192.168.0.0/16
    when: c_eng | int == 3 and n_m_nodes | int == 1

### Multi-master cluster ###
# Kubernetes Master nodes bootstrap with kubeadm and Docker
  - name: Initialize the Kubernetes cluster using kubeadm and Docker
    command: kubeadm init --control-plane-endpoint 172.16.3.5 --upload-certs --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name {{ hostname }} --pod-network-cidr=192.168.0.0/16
    when: c_eng | int == 1 and n_m_nodes | int > 1

# Kubernetes Master nodes bootstrap with kubeadm and containerd
  - name: Initialize the Kubernetes cluster using kubeadm and containerd
    command: kubeadm init --control-plane-endpoint 172.16.3.5 --upload-certs --cri-socket=/run/containerd/containerd.sock --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name {{ hostname }} --pod-network-cidr=192.168.0.0/16
    when: c_eng | int == 2 and n_m_nodes | int > 1

# Kubernetes Master nodes bootstrap with kubeadm and CRI-O
  - name: Initialize the Kubernetes cluster using kubeadm and CRI-O
    command: kubeadm init --control-plane-endpoint 172.16.3.5 --upload-certs --cri-socket=/var/run/crio/crio.sock --apiserver-advertise-address="{{ node_ip }}" --apiserver-cert-extra-sans="{{ node_ip }}" --node-name {{ hostname }} --pod-network-cidr=192.168.0.0/16
    when: c_eng | int == 3 and n_m_nodes | int > 1

  - name: Setup kubeconfig for user
    command: "{{ item }}"
    with_items:
     - "mkdir -p /home/{{ user }}/.kube"
     - "cp -i /etc/kubernetes/admin.conf /home/{{ user }}/.kube/config"
     - "chown {{ user }}:{{ user }} /home/{{ user }}/.kube/config"

# Allow pods to run on the master node in case there are no worker nodes
  - name: Allow pods to run on the master node
    command: kubectl taint nodes --all node-role.kubernetes.io/master-
    when: n_w_nodes | int == 0

# Install the CNI network plugin

# Calico
  - name: Install Calico CNI plugin
    become: false
    retries: 3  
    shell: |
      kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
      kubectl create -f https://docs.projectcalico.org/manifests/custom-resources.yaml
    when: cni | int == 1

# Cilium
  - name: Install Cilium CNI plugin
    become: false
    retries: 3  
    shell: |
      kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.9/install/kubernetes/quick-install.yaml
    when: cni | int == 2

# Weawe
# IMPORTANT: only for Kubernetes v1.6+
# Otherwise use: kubectl apply -f https://git.io/weave-kube
  - name: Install Weave CNI plugin
    become: false
    retries: 3  
    shell: |
      kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    when: cni | int == 3

# Flannel
# IMPORTANT: only for Kubernetes v1.17+
  - name: Install Flannel CNI plugin
    become: false
    retries: 3  
    shell: |
      kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    when: cni | int == 4

# Generate join command for worker nodes
  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

# Generate join command for the other master nodes
  - name: Generate join-command for other master nodes
    command: kubeadm init phase upload-certs --upload-certs
    register: join_command_master
    when: n_m_nodes | int > 1

  - name: Copy join-command for other master nodes
    become: false
    local_action: copy content="{{ join_command_master.stdout_lines[-1] }}" dest="./join-command-master"
    when: n_m_nodes | int > 1

  - name: Install Helm package manager (1/2)
    get_url:
      url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      dest: "/home/{{ user }}/get_helm.sh"
      mode: '0700'
    retries: 3  
    ignore_errors: yes

  - name: Install Helm package manager (2/2)
    command: ./get_helm.sh
    retries: 3  
    ignore_errors: yes

  - name: Add default repository
    command: helm repo add stable https://charts.helm.sh/stable
    retries: 3  
    ignore_errors: yes

  - name: Install open-iscsi and nfs-common
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - open-iscsi
      - nfs-common
