---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

# Install the Container Runtime Engine

# Docker
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    when: c_eng == 1 

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    when: c_eng == 1 

# Specify Docker version
# To list the available versions in the repo run # apt-cache madison docker-ce
  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce=5:20.10.7~3-0~ubuntu-xenial
      - docker-ce-cli=5:20.10.7~3-0~ubuntu-xenial
      - containerd.io=1.4.6-1
    when: c_eng == 1
      
  - name: Add user to docker group
    user:
      name: "{{ user }}"
      group: docker
    when: c_eng == 1
  
  - name: Set Docker cgroup driver to systemd
    blockinfile:
      path: /etc/docker/daemon.json
      create: yes 
      block: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
    when: c_eng == 1

  - name: Delete Ansible marker in /etc/docker/daemon.json
    lineinfile:
      path: /etc/docker/daemon.json
      regexp: "ANSIBLE" 
      state: absent
    when: c_eng == 1

# containerd
  - name: Set-up containerd prerequisites
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
      overlay
      br_netfilter
      EOF
      sudo modprobe overlay
      sudo modprobe br_netfilter
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF
      sudo sysctl --system
    when: c_eng == 2

  - name: Install containerd
    shell: |
      wget https://github.com/containerd/containerd/releases/download/v1.5.5/cri-containerd-cni-1.5.5-linux-amd64.tar.gz

      sudo tar --no-overwrite-dir -C / -xzf cri-containerd-cni-1.5.5-linux-amd64.tar.gz
      rm *
      
      sudo systemctl daemon-reload
      sudo systemctl start containerd
    when: c_eng == 2

# CRI-O
  - name: Set-up CRI-O prerequisites
    shell: |
      cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
      overlay
      br_netfilter
      EOF
      sudo modprobe overlay
      sudo modprobe br_netfilter
      cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      EOF
      sudo sysctl --system
    when: c_eng == 3

  - name: Add CRI-O repositories
    shell: |
      export OS=xUbuntu_20.04
      export VERSION=1.20

      echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:$VERSION.list
    when: c_eng == 3 

  - name: Add CRI-O repository key
    shell: |
      export OS=xUbuntu_20.04
      export VERSION=1.20

      curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | apt-key add -
      curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/Release.key | apt-key add -
    when: c_eng == 3 

  - name: Install CRI-O
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - cri-o
      - cri-o-runc
    when: c_eng == 3
      
  - name: Enable CRI-O service
    shell: |
      sudo systemctl daemon-reload
      sudo systemctl enable crio --now
    when: c_eng == 3

  - name: Use cgroup driver for CRI-O 1/2
    ansible.builtin.lineinfile:
      path: /etc/crio/crio.conf
      regexp: '^conmon_cgroup ='
      line: conmon_cgroup = "pod"
    when: c_eng == 3

  - name: Use cgroup driver for CRI-O 2/2
    ansible.builtin.lineinfile:
      path: /etc/crio/crio.conf
      regexp: '^cgroup_manager = "systemd"'
      line: cgroup_manager = "cgroupfs"
    when: c_eng == 3

  - name: Restart crio
    service:
      name: crio
      daemon_reload: yes
      state: restarted
    when: c_eng == 3

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap for the kubelet
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

# Evetually, specify a specific version to be installed as following
# kubelet=<version>
  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet=1.20.0-00
        - kubeadm=1.20.0-00
        - kubectl=1.20.0-00
  
  - name: Avoid automatic updates for kuebelt, kubeadm, and kubectl
    command: sudo apt-mark hold kubelet kubeadm kubectl

  - name: Configure node ip for the kubelet
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      create: yes

  - name: Restart Docker service
    shell: |
      systemctl enable docker
      systemctl daemon-reload
      systemctl restart docker
    when: c_eng == 1

  - name: Create systemd file for containerd
    blockinfile:
      path: /etc/systemd/system/kubelet.service.d/0-containerd.conf
      create: yes 
      block: |
        [Service]
        Environment="KUBELET_EXTRA_ARGS=--container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock"
    when: c_eng == 2 

  - name: Delete Ansible marker in 0-containerd.conf
    lineinfile:
      path: /etc/systemd/system/kubelet.service.d/0-containerd.conf
      regexp: "ANSIBLE" 
      state: absent
    when: c_eng == 2

  - name: Restart containerd
    service:
      name: containerd
      daemon_reload: yes
      state: restarted
    when: c_eng == 2 

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Copy the join command to server location
    copy:
      src: join-command
      dest: /tmp/join-command.sh
      mode: '0700'

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

  - name: Install open-iscsi and nfs-common
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - open-iscsi
      - nfs-common
